### ISSUE TITLE
Suggestion: do not switch view to next error location automatically

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#1]
When an error is resolved, the view is automatically moved to the next error's location in the document.

However, sometimes additional operations need to be performed at the last error's location. Therefore, navigation can sometimes become a little confusing.

My suggestion is to leave the view as is when an error is resolved, or for this to be an option the user can switch on/off.

**Comment by gsautter** [comment]
You got it ... I added a checkbox for automated selection of next error (blue box), and I also added some clarification to the "False Positive" button (red box), now explicitly also including the possibility of an error in the underlying document rather than the markup:
![image](https://user-images.githubusercontent.com/5789714/62258001-97bd1480-b408-11e9-868a-85ccab224c5f.png)
Comes with next build.
