### ISSUE TITLE
Error: Treatment has broken inner structure

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#16]
Can not determine exact nature of error. However, `Tools` --> `Treatment Structure` shows different subsubsections than viewing their attributes in the .imf view.

In: `zootaxa.4590.5.2`

**Comment by gsautter** [comment]
You are talking about the `type` attribute, I take it? Are you talking about the attributes _set_ on the annotations, or the options available in the drop-downs? The latter may well differ because in the structuring tool, the selection of types comes from a configured list, whereas the drop-down in "Edit Attributes" (a completely generic function) is populated solely from what's present elsewhere in the document proper.

**Comment by gsautter** [comment]
OK, got it ... problem was that the terminal period of the "Biology" paragraph wasn't included in the `subSubSection` spanning that whole paragraph ... simply selecting across the words and "Extend subSubSection" fixed the problem. Easier to see at 200% zoom ... however, the XML view also shows it if you fire up the tags, easier to see there.
