### ISSUE TITLE
Error: Taxonomic Key treatment with broken structure

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#2]
Treatment markup breaks inside the key for some reason.

In: zootaxa.4585.1.10

**Comment by gsautter** [comment]
Mind to elaborate? Maybe we can do this via Skype?

**Comment by brokentool** [comment]
We looked at this document during the last Skype call and decided that you should take a look. I was supposed to open this issue and mention the particular document for you to investigate.

I am unsure what the error is, the key is not tagged as such in its entirety.

And I just stumbled on a similar issue in another document: zootaxa.4585.3.7

**Comment by gsautter** [comment]
Ah, OK, thanks, I'll look into it.

**Comment by gsautter** [comment]
Fixed `zootaxa.4585.3.7`, there was an issue with keys that have both leads in a step numbered and have a step continuing across a page (or column) break.

**Comment by gsautter** [comment]
`zootaxa.4585.1.10` is a different matter, though: For one, a page break through a key _lead_ is something pretty rare, but the ultimate stumbling block are the interspersed remarks, which are left oriented instead of the usual justified layout. The latter kicks a filter into action that is intended to prevent false positives. I'll try and think up some solution.

**Comment by gsautter** [comment]
Fixed `zootaxa.4585.1.10` as well now. The catch is to go more lightly on such interspersed short lines in user interaction than in batch mode, with the rationale that a user will spot any false positives before they end up in TB and elsewhere.
