### ISSUE TITLE
Bug: Separation of images and text

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#27]
In the last few days of using the tool I noticed that there are many, many instances where the image region also captures text above the image, and its caption, inside the image region.

Not sure why I did not notice this earlier, but it seems in the last week I've had tons of errors where the text inside the image region breaks the overall text flow. See attached example.

![scrn07](https://user-images.githubusercontent.com/22291049/64783271-152f8500-d570-11e9-9eff-9d337f9f72c5.png)

**Comment by gsautter** [comment]
I'm aware of the problem, it's cause by too close proximity of the text to the bitmap. There is some "adhesion" built in so, for instance, an axis label stays with a vector graphics diagram. In this case, this is obviously a problem.

There should be functionality in document structure detection that cleans this up automatically, but it could be the respective documents were processed before I built in the latter ... anyway, if you could put a few names of affected documents here, I'll test the cleanup function on them and refine it if required. Maybe I need to use different grades of "adhesion" with vector graphics and images, respectively.

**Comment by brokentool** [comment]
I will look out for good examples. When I posted this issue, it was after I went through 5-6 documents where almost all images has this problem

**Comment by gsautter** [comment]
Please also try running "Tools > Detect Document Structure" on those documents ... odds are that will fix the problem.

**Comment by brokentool** [comment]
a good example in: `zootaxa.4624.1.3`

did not run "Detect Document Structure" so that you can check it out. already fixed 2 pages where image region was extended over text, document has 4-5 more.

also noted that it happens when you have two images with two captions on the same page, where one image region captures all elements.

**Comment by gsautter** [comment]
"Detect Document Structure" readily fixes `zootaxa.4624.1.3`, and I presume it will fix the others as well.

Now all I have to do is to _prevent_ such havoc from happening in the first place ... time to take on the PDF decoder.

**Comment by gsautter** [comment]
Turns out the problem actually is not artificial "adhesion" at all ... it's plainly that page blocking doesn't find large enough a gap between the figure image and the surrounding text to justify a block split because the figure image is about as far away from the text as the distance between two lines inside a paragraph. Using that low a threshold would also rip apart regular text paragraphs.

**Comment by gsautter** [comment]
Now trying to include the repair code from "Detect Document Structure" in PDF decoding proper ...

**Comment by gsautter** [comment]
Disregarding the figures during page structure detection (the part of PDF decoding that generates the columns, blocks, and paragraphs) appears to do the trick. However, we have to keep an eye on this one for a little because there might be cases where observing the figures might yield the better results.

**Comment by brokentool** [comment]
should this one still be open?

**Comment by gsautter** [comment]
Most likely not ... was just the "need to observe for a little" part that kept me from closing this one.
