### ISSUE TITLE
Bug: Article cut short at last page

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#39]
In: `zootaxa.4638.3.3`

Last reference is not complete, I'm guessing at least one page is missing from document.

It is a first, so I thought to point it out

**Comment by gsautter** [comment]
This is indeed a first ... however, the page number of the last page ("378") is in line with the pagination indicated in the article header ("351–378"), so I tend to think this is an editorial error rather than a decoding mishap ... a look at the PDF in Acrobat confirms this:
![image](https://user-images.githubusercontent.com/5789714/65340084-bd2afb00-dbcd-11e9-8a50-b510b165df89.png)
