### ISSUE TITLE
Error: punctuation mark missing

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#4]
Found a new error type, with which I am unsure how to proceed.

Moreover, it appears that a punctuation mark is expected at the end of titles and other elements that do not usually include such.

edit: document is: zootaxa.4590.2.3
edit2: error pops up after using "Re-Check" on documents that do not previously contain such errors

![scrn05](https://user-images.githubusercontent.com/22291049/62685836-14815d00-b9cc-11e9-8171-9f98f79295f1.png)

**Comment by gsautter** [comment]
That's definitely not a bug ... it's a new feature that came in with this morning's update. Here, it hints you to a paragraph break inside the title, which shouldn't be there.

I've realized this gives a good few false positives especially in the article head, and also in keys and bibliography, but also identifies these few problematic page breaks that otherwise interfere with materials citations, etc. It's for test right now, pending refinement, but ultimately I think it'll be pretty helpful.

**Comment by brokentool** [comment]
Thanks for the explanation, I think I understand why it is so.. strict. Will mark false positives as such, will address the rest of the errors accordingly.

I guess that if I re-check the documents I have already cleared of Blockers and Criticals, this new type of error will crop up. Do you think I should do that? Otherwise issue can be closed, IMO.

**Comment by gsautter** [comment]
I don't think you need to re-check anything. Trust that if there were any actual paragraph break issues, you'd have stumbled across them already because they tend to have nasty downstream effects. These new checks are simply intended to help you spot such issues more easily.

Ultimately, we shall observe what the most frequent reasons for false positives are and then refine the rules accordingly. Better overly strict up front to make sure the rules do what they are supposed to, and then weed out the most frequent or obvious false positives to make your life easier.
