### ISSUE TITLE
Bug: Treatment citations on several lines start paragraphs with each line

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#40]
In: `zootaxa.4646.2.4`

Noted in a lot of documents: when a citation below the nomenclature spans two or more lines, each line starts a new paragraph. It's not in 100% of cases, but a lot.

![scrn12](https://user-images.githubusercontent.com/22291049/65326250-b2ff0180-dbb9-11e9-89d9-48054ec0c283.png)

**Comment by gsautter** [comment]
Looks like the statistical block layout analysis goes wrong here ... namely mistaking the block for having indented paragraph starts rather than outdented ones.

**Comment by gsautter** [comment]
Verified ... the problem is that most of these reference group blocks contain very few lines, and thus statistical layout analysis has too small a sample for reliable conclusions. On top of this, paragraphs are one or two lines at most, in contradiction to pretty much all flowing text. To complicate matters even further, only very few of the wrapped lines actually start with a lower case word that would identify them as paragraph continuations ... will see what I can do.

**Comment by gsautter** [comment]
A good way of dealing with such paragraph errors is to show both `block` and `paragraph` regions and then use "Revise Block Paragraphs", which allows you to specify the layout and then applies it.
