### ISSUE TITLE
Vertical text direction?

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#43]
In: `zootaxa.4652.3.1`

See Text Stream Critical errors in document. There is a rotated table, and caption text flows from bottom of page towards the top. Text Stream errors show that Imagine is trying to read the text as if going left-to-right. How do we deal with this?

**Comment by gsautter** [comment]
Problem is that the table comes as a bitmap ... otherwise, the whole thing, including the caption, would be rotated to horizontal on decoding ... on the other hand, that also happens to figures ... will check why this mechanism didn't kick in in this case.

**Comment by gsautter** [comment]
Apart from that, this document is a good bit strange ... some lines at the top of pages are cut out as artifacts, apparently because they are higher up on the page than the template expects content. Pages 30, 31, 33, 35, 37, and 39-41. All in all an editorial nightmare this one ... first instance I see where some basic layout aspect like page content area is violated.

Fixed the whole thing now, apart from the bitmap table, which is next.

**Comment by gsautter** [comment]
Like I suspected, the bitmap is upright (with bottom-up content), tilting the majority vote on the orientation of the whole block ... preciously little we could do about this one, I'm afraid. I removed all the text stream errors as false positives.
