### ISSUE TITLE
Error: MC boudaries are broken

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#44]
In: `zootaxa.4664.3.11` (only Critical in document)

A really short MC, but I could not find out why its boundaries are broken.

**Comment by gsautter** [comment]
Very subtle one ... this `materialsCitation` includes two meter based lengths: "0-1000m", the actual elevation, and "3300m", the distance from the fishing trawler or from the coast (cannot tell which, but that doesn't really matter in the current context anyway).
There is a check that fires a potential error if there is more than one potential elevation, i.e., a length in the meter or foot range, as distances are usually given in kilometers or miles, at least on land. So this one is a false positive, caused by a second distance given in meters or feet.
