### ISSUE TITLE
Bug: Figure caption not entirely present

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#47]
In: `zt01161p064`

The first line of the caption is missing. See the one Critical error remaining

![scrn16](https://user-images.githubusercontent.com/22291049/66113084-c73cf880-e5d4-11e9-8a72-c83f2693f7e1.png)

**Comment by brokentool** [comment]
second one in: `zt01164p033` page 13

**Comment by gsautter** [comment]
We've had this before ... used to happen when the caption text overlapped with the (usually white) outskirts of a bitmap figure. Was fixed a good while ago by introducing observance of clipping into overlap computation, but there might be some older documents left that have respective errors.

I'll fix these guys myself, since it requires adding the missing words as well, which is a bit tricky.

**Comment by gsautter** [comment]
Fixed ... this kind of thing requires modifying the IMF in a text editor ... if you're interested, I can show you how to do it next time I'm in Sofia, but it's a bit complicated.
