### ISSUE TITLE
Bug?: Can not open MCTagger in XML view

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#48]
In: `zt01162p064`

can not open Tagger for the MC in XML view.

**Comment by gsautter** [comment]
In which XML view exactly? I mean the XML view of what? The whole document, or some treatment or subSubSection? In the latter case, which one is it?

**Comment by brokentool** [comment]
Opening XML view of the Material Citation, only Critical error in document left

**Comment by gsautter** [comment]
OK, got it ... this is actually intended behavior, if for pretty much legacy reasons. The MC tagger works either on a treatment as a whole, or on individual paragraphs, the former for regular from-scratch markup, the latter for correcting errors. Since this specific materials citation spanned multiple paragraphs, but without the context of a treatment, the MC tagger skips over it. This behavior was originally intended to be able to start over where you left off in large XML documents ... as mentioned before, legacy reasons.

The whole materials citation facilities are due for a makeover anyway (unify detail tagging behavior, etc.), and I'll take care of this logic in the process.

**Comment by brokentool** [comment]
closing this one, then
