### ISSUE TITLE
list of error types checked

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-qualitycontrol#57]
@gsautter can you please provide a list of the errors that are being checked, that is a description what kind of errors that are covered?

**Comment by gsautter** [comment]
Document Metadata:
- Identifiers (all CRITICAL errors):
  - check if the document has a DOI
  - check if the document has a Zenodo deposition ID
- Bibliographic Metadata (all BLOCKER errors unless indicated otherwise):
  - check if the document has at least one author
  - check if the document has a title
  - check if the document has a year
  - check if the document has a publication date (CRITICAL error if absent)
  - check if the document has a pagination
  - check if the document has a journal name
  - check if the document has a volume number

Text Streams:
- Paragraph Starts:
  - check if any paragraphs start with a lower case word longer than one character (CRITICAL error on paragraph if they do)
- Paragraph Ends:
  - check if each main text paragraph (outside a key or heading) ends with a period, colon, or exclamation or question mark (CRITICAL error on paragraph if they don't)

Illustrations:
- Captions:
  - check if captions have attributes linking it to image, graphics, or table (CRITICAL error if not)
  - check if captions assigned to images or graphics have an HTTP URI (MAJOR error if not)
  - check if captions are referenced by at least one figureCitation or tableCitation (MAJOR error on caption if not)
  - check if paragraphs starting with an emphasized caption start keyword ('Figure', 'Table', etc.) are marked as captions (CRITICAL error on paragraph if not)
- Caption Citations:
  - check if figureCitations and tableCitations are linked to captions (CRITICAL error on citation if not)
  - check if figureCitations have an HTTP URI (MAJOR error if not)

Bibliographic References:
- Bibliography (all CRITICAL errors unless indicated otherwise, all per reference):
  - check if each reference has an author
  - check if each reference has a title
  - check if each reference has a year of publication
  - check if each reference has a document internal ID (added by citation tagging)
  - check if each reference is cited by at least one bibRefCitation (MAJOR error on reference if not)
- Bibliographic Citations:
  - check if each bibRefCitation is linked to a reference (CRITICAL error on citation if not)

Taxonomic Names (all BLOCKER errors on taxon names in treatment nomenclature, CLRITICAL errors in treatment reference group, MAJOR errors elsewhere in treatments, and MINOR errors outside treatments):
- check if each taxon name has rank attribute
- check if each taxon name has a taxonomic kingdom assigned to it
- check if each taxon name has proper authority information assigned to it
- check if each taxon name of rank family or below has a taxonomic family assigned to it

Treatments:
- check if boundaries of each treatment coincide with paragraph starts and ends (CRITICAL error if not)
- check if each treatment is structured into subSubSections (BLOCKER error if not)
- check if each treatment completely structured into subSubSections (CRITICAL error if not)
- check if boundaries of each treatment subSubSection coincide with paragraph starts and ends (CRITICAL error if not)
- check if each treatment has a nomenclature subSubSections (BLOCKER error if not)
- check if each treatment has a taxon name inside its nomenclature subSubSections (BLOCKER error if not)
- check if each treatment stating '<rank> nov.' subSubSections has a materials citation with type status holotype (CRITICAL error if not)

Materials Citations:
- check if materials citations have repeated detail elements indicating a missing split (CRITICAL error if so)
  - more than one type status
  - more than one country
  - more than one regions
  - more than one coordinate pair (i.e., two coordinates)
  - more than one elevation
  - more than one collector or determiner name label ('leg.', 'det.', etc.)
- check if coordinates in materials citations are either absent or present as a pair (CRITICAL error if not)

**Comment by gsautter** [comment]
Above list is subject to extension, refinement, and revision as the need arises, of course ... this is the things I could think of as a starting point when we introduced error checking, together with my perceived levels of error severity.

**Comment by myrmoteras** [comment]
@gsautter this is cool and remarkable! tx

**Comment by brokentool** [comment]
closing this one?
