### ISSUE TITLE
Suggestion: Lock highlights selection

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#61]
I would love it if there was the option to lock one's highlight selection, because there are too many actions that change it.

For some actions, like resolving text stream errors, I would like to be able to, for example, use only the "word" highlight (topmost), but every time I resolve an error, it brings back highlights like `docAuthor`, `docTitle`, `heading`, etc.

**Comment by gsautter** [comment]
Well, this behavior sounds pretty strange to me ... in general, the only time GGI automatically activates some highlight is when a gizmo changes annotations, so the user can see the changes right away. Not sure how working on text streams would modify `docAuthor`, `docTitle`, etc., as those belong to the metadata. Which document did you observe this with?

**Comment by brokentool** [comment]
any one document. picking at random: `zootaxa4695.6.5`

I open the document, then go to text stream errors and click on the first error. See screenshot below for results:

![scrn22](https://user-images.githubusercontent.com/22291049/72722005-fe381980-3b85-11ea-965f-db16a4babd66.png)

**Comment by gsautter** [comment]
Ah, got it ... indeed, this might be a bit strange, but it's actually intentional (I just didn't think of it last week): whenever you select an error category, all the annotations involved in the respective checks are highlighted so you can see what the errors are about.

In case of the text streams, this might indeed be a bit odd, but the three types `docTitle`, `docAuthor`, and `heading` are involved in this check because they are _exempt_ from the "paragraph requires terminating punctuation mark" check.

I can add a checkbox to the error list that would deactivate highlighting the annotations involved in error checks, but are there any error categories other than the text streams where _not_ highlighting the annotations would make sense?

**Comment by brokentool** [comment]
good question. will get back to you on that, after mote testing

edit: maybe another element to consider should be the author affiliations on the title page, since currently they are a part of the text stream errors, while almost 100% of them end with a parenthesis or similar, but not periods. also, perhaps reference groups as well?

**Comment by brokentool** [comment]
> are there any error categories other than the text streams where not highlighting the annotations would make sense?

one error category that could benefit from this is MCs. sometimes I do not need every element of a MC highlighted. examples: collectingCountry; collectingDate, collectionCode, etc. sometimes these can help, but it would be nice to be able to have them NOT turn on when you select every consecutive error in the category

**Comment by gsautter** [comment]
You got a point there ... however, implementing such functionality would basically require specifying which annotations to show for each type of error ... maybe an option for a future revision, but definitely a good bit of effort for relatively few cases.
