### ISSUE TITLE
Error: Can not assing caption to target

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#62]
In: `zootaxa.4691.4.2`

Currently, only three critical errors are for three captions, not assigned to a target.

Could not figure out why I can not assign the captions to their respective tables. When I use "assign caption" and click on the caption, nothing happens. It **did** work for the first table, but only for that one.

**Comment by brokentool** [comment]
also here: `zootaxa.4691.5.3`

could not link figure 8 to its caption.

one more example: `zootaxa.4695.1.2`: only three criticals in the document

..they just come up as I move through the docs: `zootaxa.4695.2.1`, caption for table 1

`zootaxa.4695.23`, only four ciritcals

**Comment by gsautter** [comment]
I guess this explains it all (Table 2 in zootaxa.4691.4.2):
![image](https://user-images.githubusercontent.com/5789714/72641587-d0c35400-396a-11ea-97d5-97b14e8e1287.png)
"Merge Captions" fixes this right away.

Tables 3 and 4 are a different issue ... while _annotated_ as a caption, it's still part of the main text (gray). "Mark Caption" fixes these two.

**Comment by gsautter** [comment]
Looking at the others now ...

**Comment by gsautter** [comment]
In `zootaxa.4695.2.10`, a simple "Mark Citations of Table" did the trick.

In `zootaxa.4695.2.1`, the caption again was only annotated as such, but still part of the main text ... as above, "Mark Caption" fixes this right away.

In `zootaxa.4695.2.3`, again "Mark Caption" did the trick, and also in `zootaxa.4695.1.2`.

Please use "Mark Caption" (magenta context menu item) instead of "Annotate > Caption", as the latter only creates the annotation, while the former also cuts the caption out of the main text and takes care of target assignment.
