### ISSUE TITLE
Error: Can not mark full image

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#64]
In: `zootaxa.4705.1.1`

See screenshot. Tried a couple of times to mark the full image, but it always crops only the top left part. Did not have the option to mark graphics in the context menu, when I removed the image region and tried to go with mark graphics

![scrn23](https://user-images.githubusercontent.com/22291049/72802618-dc599800-3c54-11ea-8f4d-56ef615cb6ad.png)

**Comment by gsautter** [comment]
This whole thing indeed comes as a bitmap, so it's normal you cannot mark a graphics object. However, why the size shrinks to the top left corner is something I'll have to investigate ... could be the somewhat light colors of the bitmap are to blame here ... the box shrinks to the exact extent of the somewhat darker colors (purple and black) in the upper left corner.

**Comment by gsautter** [comment]
On the upside, though, you can assign the caption target, and the figure image exports just fine.

**Comment by gsautter** [comment]
Fixed ... was a weird issue in the routine intended to remove any white edges from bitmaps to prevent interference with text. In particular, said routine didn't get along specifically with pure full-brightness blue, which is why we didn't realize the issue in a long while ... how often do you encounter a bitmap larger with areas in nothing but that color and actual white?

Anyway, it's fixed now ... comes with next update.

**Comment by brokentool** [comment]
definitely a first, this one

**Comment by gsautter** [comment]
Or as I've come to put it: The data _never_ runs out of surprises ... ;-)
