### ISSUE TITLE
Bug: Broken geo coordinates

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#65]
In: `zootaxa.4706.2.9` (only criticals left)

so IIRC coordinate pairs should be tagged into a single highlight. after doing so, the errors remain. this happens **every time** for this type of error. am I doing something wrong?

**Comment by gsautter** [comment]
Nope, please mark each coordinate individually, one is longitude, one is latitude, and that reflects in the respective `orientation` attributes ... and since the tagger marks them this way, why did you merge them? And if you didn't, I'm left to wonder how this happened ... anyway, re-running the coordinate tagger fixed it right away.

In fact, one check for broken coordinates is whether there are exactly zero or exactly two because they always come in pairs ...

**Comment by brokentool** [comment]
no, it was me, I was under a severely wrong impression, for which I am sorry

**Comment by brokentool** [comment]
is there a way to revert my false positives in this particular error category from this week?

Once again, sorry for this. dunno how it got mixed up in my head

**Comment by gsautter** [comment]
Afraid you'll have to go back to the documents and fix them ... the best approach would likely be to re-run the coordinate tagger (in XML view "Tools > Run Analyzer") and then remove the conflated coordinate pairs ("View > Navigate Annotations" with filter `geoCoordinate[./geoCoordinate]`).
