### ISSUE TITLE
Bug: Article Title on multiple lines

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#66]
In: `zootaxa.4706.3.1`, most documents =)

when the title is on multiple lines, each line is treated as a separate paragraph. this happens **a lot**

**Comment by gsautter** [comment]
Depending on line distance and total width of the title block, yes it does. Without any ill effects on the metadata, though, as the respective extractor reads over the line breaks simply _because_ this kind of thing happens.

**Comment by gsautter** [comment]
As in `zootaxa.4706.3.1`, "reptile" would have easily fit after "... lessons from" without even getting close to the right edge of the surrounding column, so the underlying logic thinks the line break is intentional ... this approach tends to work magic in the document main text, which is far more important in terms of data extraction.
So if the authors (or the editors, whoever) insert a line feed in the title to make the lines about equally long, it is interpreted as exactly that: a line break, as word wrapping only occurs at the right edge of a text block or column. That the line break is for optics rather than semantics (usually it's the latter) is a bit hard to tell solely based upon the alignment of the words ...
