### ISSUE TITLE
Error: captions and their citations

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#80]
in: `Lambe1902BellyRiver.pdf.imf`

throughout whole document, as far as I was able to understand, there are numbered figures, but then there are plates at the end, which are divided into figures with the same labels (fig. 1, fig. 2, etc.), which means there is more than one element with the same label.

not sure how to QC this one

**Comment by gsautter** [comment]
I'd say the plates are false positives altogether, as the sub captions are most likely cited.

Plus, in such old documents, we most likely cannot apply the same standards as in more modern ones.

**Comment by gsautter** [comment]
Spent about an hour now on re-marking all the all the figure citations ... must have been done wrong the first time, as the links were just not there ...

One problem arising with automated marking of figure citations is that the citations are mostly in lower case ("fig" or "plate" instead of "Fig" or "Plate"), which is filtered out in normal markup because the lower case figure citations usually reference figures in other publications (mostly in treatment reference groups) whereas citations of figures in the publication at hand are in title case.
